services:
  - type: web
    name: yogesh-streamer-bridge
    env: node
    plan: free
    buildCommand: ""
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: 10000
      - key: APP_PIN
        value: "778899"
